# Generated by Django 5.2.12 on 2026-05-04 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_token_expire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='token_expire',
            new_name='token_expired',
        ),
    ]
